agregado app perfiles, html, css
JulianRdz00/proyecto_capa pull request #4
Opened 2022-01-14 15:32 UTC by Taborda-A-Agustin

Agregado app perfiles, agregado app en settings, config urls en perfiles, config views perfiles, cambio url de proyecto_capa, agregado index.html y modificado para base, agregado index.css para estilos puntuales, agregado bootstrap.css.

2022-01-19 01:03 UTC, ariel-llanes requested changes

2022-01-19 01:03 UTC, ariel-llanes commented on capacitaciones/settings.py
> +ALLOWED_HOSTS = ['127.0.0.1','localhost']
"*"

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/admin.py
> +# Register your models here.
Agregar modelo nuevo

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +
Falta un enter

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    nombres = models.CharField(max_length=50)
Esto esta en el modelo User

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    telefono = models.CharField(max_length=20)
null = True

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    biografia = models.CharField(max_length=500)
null = True

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +        return self.title
OMG!

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    created_date = models.DateTimeField(
Esperar a que se mergee el PR del otro grupo y utilizar la clase nueva "CommonInfo" desde libs

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +class Perfiles(models.Model):
Agregar el FK a User

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    email = models.EmailField(max_length=80)
Esta en el modelo User

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/models.py
> +    nacimiento = models.DateField(
fecha_nacimiento

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/templates/perfiles/index.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
Descargar dentro del proyecto

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/templates/perfiles/index.html
> +{% load static %}
Cambiar nombre del archivo por base y agregar los blocks de Jinja2

2022-01-19 01:03 UTC, ariel-llanes commented on perfiles/templates/perfiles/index.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
Agregar aca los bloques

{% block content %}{% endblock content %}

2022-01-20 19:22 UTC, Taborda-A-Agustin commented on capacitaciones/settings.py
> +ALLOWED_HOSTS = ['127.0.0.1','localhost']
Resuelto en proximo PR

2022-01-20 19:22 UTC, Taborda-A-Agustin commented on perfiles/admin.py
> +# Register your models here.
Resuelto en proximo PR

2022-01-20 19:22 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +
Resuelto en proximo PR

2022-01-20 19:25 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +    biografia = models.CharField(max_length=500)
Resuelto en proximo PR.

2022-01-20 19:25 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +    telefono = models.CharField(max_length=20)
Resuelto en proximo PR.

2022-01-20 19:27 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +    created_date = models.DateTimeField(
Los saqué por el momento.

2022-01-20 19:27 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +    email = models.EmailField(max_length=80)
Borrados.

2022-01-20 19:28 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +    nacimiento = models.DateField(
Cambiado.

2022-01-20 19:36 UTC, Taborda-A-Agustin commented on perfiles/templates/perfiles/index.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
Descargado y agregado.

2022-01-20 19:45 UTC, Taborda-A-Agustin commented on perfiles/templates/perfiles/index.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
Agregados

2022-01-20 20:00 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +class Perfiles(models.Model):
Hecho.

2022-01-20 20:00 UTC, Taborda-A-Agustin commented on perfiles/models.py
> +        return self.title
Borrado

2022-01-20 20:46 UTC, Taborda-A-Agustin commented
agregado index.html extendido de base.html.
Link de captura de pantalla del html: [https://ibb.co/FKFLXHK](url)

2022-01-26 00:58 UTC, Taborda-A-Agustin commented
Ultimos arreglos, autor a user, cambios de urls, settings

2022-01-26 00:59 UTC, llanesAriel approved these changes

2022-01-26 00:59 UTC, merged